### ISSUE TITLE
Chroma and PinkCore

### ISSUE THREAD

**Issue by AwesomeCE110** [BSMGPink/PinkCore#2] opened 2021-08-21 16:56 UTC
It seems as though the new Chroma mod and PinkCore are having some compatibility issues (at least for me), w/o Chroma, mapper names show up, and w/ it, they are gone, I am also reporting this issue to Fern, I hope you can figure this out. (I suspect ChromaLite may not be fully removed, but that's just a thought)

**Comment by RedBrumbler** [comment] 2021-08-22 01:13
This issue is probably (read: definitely) caused by some leftover code that is still in CJD, that was not removed and is thus causing this issue, therefore this issue will be closed as the fix is not dependent on pinkcore

**Closed by RedBrumbler** 2021-08-22 01:13 UTC
Labels: wontfix
